Update README.md

diff --git a/.github/workflows/cloc.yml b/.github/workflows/cloc.yml
--- a/.github/workflows/cloc.yml
+++ b/.github/workflows/cloc.yml
@@ -26,7 +26,7 @@ jobs:
         run: |
           curl -sLO https://github.com/vearutop/sccdiff/releases/download/v1.0.3/linux_amd64.tar.gz && tar xf linux_amd64.tar.gz
           sccdiff_hash=$(git hash-object ./sccdiff)
-          [ "$sccdiff_hash" == "8e507e0d671d4d6dfb3612309b72b163492f28eb" ] || (echo "::error::unexpected hash for sccdiff, possible tampering: $sccdiff_hash" && exit 1)
+          [ "$sccdiff_hash" == "ae8a07b687bd3dba60861584efe724351aa7ff63" ] || (echo "::error::unexpected hash for sccdiff, possible tampering: $sccdiff_hash" && exit 1)
           OUTPUT=$(cd pr && ../sccdiff -basedir ../base)
           echo "${OUTPUT}"
           OUTPUT="${OUTPUT//$'\n'/%0A}"
